name: Build Erlang §major§ for §distribution_name§/§distribution_version§

on:
  workflow_dispatch:
  repository_dispatch:
    types: [rpm_erlang_§major§]


jobs:
  call-reusable-workflow:
    uses: rabbitmq/erlang-packages/.github/workflows/gen-rpm-erlang-reusable-workflow.yml@main
    with:
      erlang_major: '§major§'
      distribution_name: '§distribution_name§'
      distribution_version: '§distribution_version§'
    secrets: inherit
