name: Build Erlang §major§ for §distribution_name§/§distribution_version§

on:
  workflow_dispatch:
  repository_dispatch:
    types: [rpm_erlang_§major§]


jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/gen-rpm-erlang-reusable-workflow.yml
    with:
      erlang_major: '§major§'
      distribution_name: '§distribution_name§'
      distribution_version: '§distribution_version§'
      publish_to_package_repos: '§publish_to_package_repos§'
    secrets: inherit
