name: Check for New Erlang Versions

on:
  schedule:
    - cron: 0 10 * * *
  workflow_dispatch:

env:
  CI_GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
  GIT_AUTHOR_NAME: ${{ secrets.RABBITMQ_CI_USERNAME }}
  GIT_AUTHOR_EMAIL: ${{ secrets.RABBITMQ_CI_EMAIL }}

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run check script
        run: |
          python ci/check-new-releases.py erlang erlang/otp
      - name: Commit changes 
        if: ${{ env.has_changed == 'true' }}
        run: |
          git config --global user.name "$GIT_AUTHOR_NAME"
          git config --global user.email "$GIT_AUTHOR_EMAIL"
          git commit -a -m "New Erlang version(s) detected"
          git push origin ${{ github.ref }}
