name: Check for New Erlang Versions

on:
  schedule:
    - cron: 0 17 * * *
  workflow_dispatch:

env:
  MK_RELEASE_AUTOMATION_TOKEN: ${{ secrets.MK_RELEASE_AUTOMATION_ERLANG }}
  GIT_AUTHOR_NAME: ${{ secrets.RABBITMQ_CI_USERNAME }}
  GIT_AUTHOR_EMAIL: ${{ vars.TEAM_RABBITMQ_EMAIL }}

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run check script
        run: |
          python ci/check-new-releases.py erlang erlang/otp
      - name: Commit changes 
        if: ${{ env.has_changed == 'true' }}
        run: |
          git config --global user.name "$GIT_AUTHOR_NAME"
          git config --global user.email "$GIT_AUTHOR_EMAIL"
          git commit -a -m "New Erlang version(s) detected"
          git push origin ${{ github.ref }}
