name: Build Erlang 25 for Ubuntu 22.04

on:
  workflow_dispatch:
    inputs:
      erlang_tag:
        description: 'Erlang OTP tag (e.g. OTP-25.3.2.7)'
        required: true
        type: string
        default: 'OTP-25.3.2.7'

env:
  ERLANG_TAG: ${{ inputs.erlang_tag != '' && inputs.erlang_tag || github.event.client_payload.tag }}

concurrency:
  group: erlang-25-deb

jobs:
  call-reusable-workflow:
    uses: rabbitmq/erlang-packages/.github/workflows/erlang-debian-package.yml@main
    with:
      erlang_tag: ${{ env.ERLANG_TAG }}
      erlang_major: '25'
      distribution_name: 'ubuntu'
      distribution_codename: 'jammy'
      distribution_version: '22.04'
    secrets: inherit
