name: Build Erlang 24 for el/9

on:
  workflow_dispatch:
  repository_dispatch:
    types: [rpm_erlang_24]


jobs:
  call-reusable-workflow:
    uses: rabbitmq/erlang-packages/.github/workflows/gen-rpm-erlang-reusable-workflow.yml@main
    with:
      erlang_major: '24'
      distribution_name: 'el'
      distribution_version: '9'
    secrets: inherit
