name: Build Erlang 26 for el/8

on:
  workflow_dispatch:
  repository_dispatch:
    types: [rpm_erlang_26]


jobs:
  call-reusable-workflow:
    uses: rabbitmq/erlang-packages/.github/workflows/gen-rpm-erlang-reusable-workflow.yml@main
    with:
      erlang_major: '26'
      distribution_name: 'el'
      distribution_version: '8'
    secrets: inherit
