name: Build Erlang 26 for el/9

on:
  workflow_dispatch:
  repository_dispatch:
    types: [rpm_erlang_26]


jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/gen-rpm-erlang-reusable-workflow.yml
    with:
      erlang_major: '26'
      distribution_name: 'el'
      distribution_version: '9'
    secrets: inherit
