name: Build Erlang 26 for El 9

on:
  workflow_dispatch:
    inputs:
      erlang_major:
        description: 'Erlang major version (e.g. 26)'
        required: true
        type: string
        default: '26'

jobs:
  call-reusable-workflow:
    uses: rabbitmq/erlang-packages/.github/workflows/rpm-erlang-reusable-workflow.yml@main
    with:
      erlang_major: ${{ inputs.erlang_major != '' && inputs.erlang_major || github.event.client_payload.major }} 
      distribution_name: 'el'
      distribution_version: '9'
    secrets: inherit
