name: Build Erlang 27 for el/9

on:
  workflow_dispatch:
  repository_dispatch:
    types: [rpm_erlang_27]


jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/gen-rpm-erlang-reusable-workflow.yml
    with:
      erlang_major: '27'
      distribution_name: 'el'
      distribution_version: '9'
      publish_to_package_repos: 'true'
    secrets: inherit
