name: Build Erlang 25 for Ubuntu 20.04

on:
  workflow_dispatch:
    inputs:
      erlang_tag:
        description: 'Erlang OTP tag (e.g. OTP-25.3.2.7)'
        required: true
        type: string
        default: 'OTP-25.3.2.7'

concurrency:
  group: erlang-25-deb

jobs:
  call-reusable-workflow:
    uses: rabbitmq/erlang-packages/.github/workflows/gen-erlang-debian-package.yml@test-build-deb
    with:
      erlang_tag: ${{ inputs.erlang_tag != '' && inputs.erlang_tag || github.event.client_payload.tag }}
      erlang_major: '25'
      distribution_name: 'ubuntu'
      distribution_codename: 'focal'
      distribution_version: '20.04'
    secrets: inherit
