name: Build Elixir 1.17 for Debian Bookworm

on:
  workflow_dispatch:
    inputs:
      elixir_tag:
        description: 'Elixir tag (e.g. v1.15.7)'
        required: true
        type: string
        default: 'v1.15.7'
  repository_dispatch:
    types: [new_elixir_1_17_release]

jobs:
  call-reusable-workflow:
    uses: rabbitmq/erlang-packages/.github/workflows/gen-deb-elixir-reusable-workflow.yml@main
    with:
      elixir_tag: ${{ inputs.elixir_tag != '' && inputs.elixir_tag || github.event.client_payload.tag }}
      distribution_name: 'debian'
      distribution_codename: 'bookworm'
      distribution_version: 'bookworm'
    secrets: inherit
