name: Build Erlang 25 for Debian Bullseye

on:
  workflow_dispatch:
    inputs:
      erlang_tag:
        description: 'Erlang OTP tag (e.g. OTP-26.2.5.4)'
        required: true
        type: string
        default: 'OTP-26.2.5.4'
  repository_dispatch:
    types: [new_erlang_25_release]

jobs:
  call-reusable-workflow:
    uses: rabbitmq/erlang-packages/.github/workflows/gen-deb-erlang-reusable-workflow.yml@main
    with:
      erlang_tag: ${{ inputs.erlang_tag != '' && inputs.erlang_tag || github.event.client_payload.tag }}
      erlang_major: '25'
      distribution_name: 'debian'
      distribution_codename: 'bullseye'
      distribution_version: 'bullseye'
      ppa_repository: 'rabbitmq-erlang-25'
      publish_to_package_repos: 'true'
    secrets: inherit
