name: Build Erlang 26 for Ubuntu 22.04

on:
  workflow_dispatch:
    inputs:
      erlang_tag:
        description: 'Erlang OTP tag (e.g. OTP-26.2.5.4)'
        required: true
        type: string
        default: 'OTP-26.2.5.4'
  repository_dispatch:
    types: [new_erlang_26_release]

jobs:
  call-reusable-workflow:
    uses: rabbitmq/erlang-packages/.github/workflows/gen-deb-erlang-reusable-workflow.yml@main
    with:
      erlang_tag: ${{ inputs.erlang_tag != '' && inputs.erlang_tag || github.event.client_payload.tag }}
      erlang_major: '26'
      distribution_name: 'ubuntu'
      distribution_codename: 'jammy'
      distribution_version: '22.04'
      ppa_repository: 'rabbitmq-erlang-26'
      publish_to_package_repos: 'true'
    secrets: inherit
