name: Build Elixir 1.15 for Debian Buster

on:
  workflow_dispatch:
    inputs:
      elixir_tag:
        description: 'Elixir tag (e.g. v1.17.3)'
        required: true
        type: string
        default: 'v1.17.3'
  repository_dispatch:
    types: [new_elixir_1_15_release]

jobs:
  call-reusable-workflow:
    uses: rabbitmq/erlang-packages/.github/workflows/gen-deb-elixir-reusable-workflow.yml@main
    with:
      elixir_tag: ${{ inputs.elixir_tag != '' && inputs.elixir_tag || github.event.client_payload.tag }}
      distribution_name: 'debian'
      distribution_codename: 'buster'
      distribution_version: 'buster'
    secrets: inherit
