name: Build Erlang 25 for el/8

on:
  workflow_dispatch:
  repository_dispatch:
    types: [rpm_erlang_25]


jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/gen-rpm-erlang-reusable-workflow.yml
    with:
      erlang_major: '25'
      distribution_name: 'el'
      distribution_version: '8'
      publish_to_package_repos: 'true'
    secrets: inherit
