name: Build Docker Image for CentOS 8

on:
  workflow_dispatch:
  push:
    paths:
      - 'docker/Dockerfile-centos-8'

jobs:
  build-docker-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile-centos-8
          platforms: linux/amd64,linux/arm64
          push: true
          tags: pivotalrabbitmq/erlang-rpmbuild-8
